*** Please tell me who you are.

Run

  git config --global user.email "darshanisoe@gmail.com"
  git config --global user.name "Darshan Raiyani"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: no email was given and auto-detection is disabled